CREATE DATABASE USER COLLATE "UTF8_GENERAL_CI"
CREATE TABLE USERS (
    ID INT(4) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50)
);


CREATE PROCEDURE `spInsertUser`(IN `_NAME` VARCHAR(50)) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER BEGIN INSERT INTO USERS (NAME) VALUES (_NAME); END;

-- CALL spInsertUser('becerra');

CREATE PROCEDURE `spFindAllUser`() NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER BEGIN SELECT ID,NAME FROM USERS; END;

-- CALL spFindAllUser();